AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template runs appache server and displays a static webpage on a single EC2 instance. 
Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0cebb45b34604efb8
      InstanceType: t2.micro
      KeyName: levo
      SecurityGroups:
       - Second_Sec_Gr
      UserData:
       'Fn::Base64': 
         !Sub |
          #!/bin/bash
          yum update -y

          # install apache
          yum install httpd -y 
            
          # start server
          service httpd start
          chkconfig httpd on
          
          #getting index.html
          cd /var/www/html 
          sudo wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html
          sudo wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          sudo wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          sudo wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg