AWSTemplateFormatVersion: 2010-09-09
Description: |
  The Phonebook Application aims to create a phonebook application 
  in Python and deployed as a web application with Flask on AWS 
  Application Load Balancer with Auto Scaling Group of Elastic 
  Compute Cloud (EC2) Instances and Relational Database Service(RDS)
  using AWS Cloudformation Service.
  
Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:  Enable HTTP for ALB
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
  
  WebserverSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP access via port 80, SSH access  
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: !GetAtt ALBSecurityGroup.GroupId
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0        


  RDSSecurityGroup:
    Type: "AWS::RDS::DBSecurityGroup"
    Properties:
      DBSecurityGroupIngress: #required
        - CIDRIP: 0.0.0.0/0
        - EC2SecurityGroupId: !GetAtt WebserverSecurityGroup.GroupId
      GroupDescription: Data Base Security Group #required
  
  WebServerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData: 
        ImageId: ami-0947d2ba12ee1ff75
        InstanceType: t2.micro
        KeyName: levo
        SecurityGroupIds: 
          - !GetAtt WebserverSecurityGroup.GroupId
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub Web Server of ${AWS::StackName} 
        UserData: 
          Fn::Base64:
            !Sub |
              #! /bin/bash

              yum update -y
              yum install python3 -y
              pip3 install flask
              pip3 install flask_mysql
              cd /home/ec2-user
              echo "${RDSinstance.Endpoint.Address}" >> dbserver.endpoint
              mkdir templates
              cd templates 
              wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/004-phonebook-web-application/templates/add-update.html
              wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/004-phonebook-web-application/templates/delete.html
              wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/004-phonebook-web-application/templates/index.html              
              cd ..
              wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/004-phonebook-web-application/phonebook-app.py
              python3 phonebook-app.py

  WebServerTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Port: 80
      Protocol: HTTP
      TargetType: instance
      VpcId: !GetAtt WebserverSecurityGroup.VpcId

  ApplicationLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups:
        - !GetAtt ALBSecurityGroup.GroupId
      Subnets:
        - subnet-10e84876
        - subnet-2c832e73
        - subnet-1b75812a
        - subnet-0ab4c447
        - subnet-6172dd40
        - subnet-26bf2528
      Type: application

  ALBListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions: #required
        - TargetGroupArn: !Ref WebServerTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ApplicationLoadBalancer #required
      Port: 80 #required
      Protocol: HTTP #required​

  WebServerASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AvailabilityZones:
        !GetAZs ""
      DesiredCapacity: 2
      HealthCheckGracePeriod: 90
      HealthCheckType: ELB
      LaunchTemplate: 
        LaunchTemplateId: !Ref WebServerLaunchTemplate
        Version: !GetAtt WebServerLaunchTemplate.LatestVersionNumber
      MaxSize: 3 #required
      MinSize: 1 #required
      TargetGroupARNs:
        - !Ref WebServerTargetGroup

  RDSinstance:
    Type: "AWS::RDS::DBInstance"
    DeletionPolicy: Delete
    Properties:
      AllocatedStorage: "20"
      BackupRetentionPeriod: 7
      #DBInstanceIdentifier: phonebook-app-db2
      DBInstanceClass: db.t2.micro #required
      DBName: phonebook
      DBSecurityGroups: 
        - !Ref RDSSecurityGroup
      #DeleteAutomatedBackups: true
      #DeletionProtection: true
      Engine: mysql
      EngineVersion: "8.0.19"     
      MasterUserPassword: "clarusway-1"
      MasterUsername: "admin"
      Port: "3306"
      #PreferredBackupWindow: "01:00-02.00"
      #PreferredMaintenanceWindow: "mon:03:00-mon:04.00"
      PubliclyAccessible: True
    
Outputs:
  WebsiteURL:
    Description: Phonebook Application Load Balancer URL
    Value: !Sub 
      - http://${ALBaddress}
      - ALBaddress: !GetAtt ApplicationLoadBalancer.DNSName
  RDSendpoint:
    Description: Phonebook DB endpoint
    Value: !Sub
      - http://${DBaddress}
      - DBaddress: !GetAtt RDSinstance.Endpoint.Address