AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template runs appache server and displays a static webpage on a single EC2 instance.

Parameters:
  ConverterKey:
    Description: Key files parameters
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: 

Resources:
 ConverterSecGr:
  Type: "AWS::EC2::SecurityGroup"
  Properties:
    GroupDescription: Allows SSH and HTTP #required
    GroupName: Kittens_Sec_Group
    SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: "80"
      ToPort: "80"
      CidrIp: 0.0.0.0/0
    - IpProtocol: tcp
      FromPort: "22"
      ToPort: "22"
      CidrIp: 0.0.0.0/0        
 WebServerInstance:
  Type: "AWS::EC2::Instance"
  Properties:
    ImageId: ami-0c94855ba95c71c99
    InstanceType: t2.micro
    KeyName: !Ref "ConverterKey"
    SecurityGroups:
    - Ref: ConverterSecGr
    Tags:
     - Key: "Name"
       Value: !Join
         - " "
         - - "Web Server of"
           - !Ref "AWS::StackName"
    UserData:
        'Fn::Base64': 
          !Sub |
 

           #getting index.html, result.html, converter_app.py
           
           
           cd /var/www/html 
           sudo wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/index.html
           sudo wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
           sudo wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
           sudo wget https://raw.githubusercontent.com/charliefalcon/aws-devops-workshop/master/aws/projects/101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
Outputs:
  PublicDNS:
    Description: Public DNS Name of the EC2 instance
    Value: !Join 
      - "://"
      - - "http"
        - !GetAtt WebServerInstance.PublicDnsName